name: Run R Code and Save Artifacts

on:
  workflow_dispatch:

jobs:
  run-r:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.posit.co/cran/latest
      RENV_CONFIG_INSTALL_STAGED: false
      RENV_CONFIG_CACHE_SYMLINKS: FALSE
      RENV_ROBOCOPY_SAFETY: false
      RENV_CONFIG_VERBOSE: TRUE
      RENV_CONFIG_PACKAGE_TYPE: binary

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3'  # version on DAC website
  
      - name: Set up pandoc (if needed for reports)
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libharfbuzz-dev libfribidi-dev libfreetype6-dev \
            libpng-dev libtiff5-dev libjpeg-dev \
            libudunits2-dev libgdal-dev gdal-bin \
            libgeos-dev libproj-dev libgettextpo-dev gettext \
            gfortran
  
      - name: Set up R dependencies with renv
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore()'
  
      - name: Run R code
        run: Rscript R/CHIS_private.R
  
      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: r-output-files
          path: Outputs/
